language: android
android:
  components:
    - build-tools-19.0.3
    - extra-google-m2repository
    - extra-android-m2repository
    - android-16
    - sysimg-16
  licences:
    - android-sdk-license-bcbbd656
    - '.*intel.+'

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#selendroid"
    on_success: always
    on_failure: always
    use_notice: true
  
branches:
  only:
    - master

before_install: 
  - "git clone -b travis `git config --get remote.origin.url` target/travis"

script: 
  - "cd android-driver"
  - "gradle clean build"
  - "cd .."
  - "cd selendroid-client"
  - "gradle clean build"
  - "cd .."
  - "cd selendroid-common"
  - "gradle clean build"
  - "cd .."
  - "cd selendroid-grid-plugin"
  - "gradle clean build"
  - "cd .."
  - "cd selendroid-server"
  - "gradle clean build"
  - "cd .."
  - "cd selendroid-server-common"
  - "gradle clean build"
  - "cd .."
  - "cd selendroid-standalone"
  - "gradle clean build"
  - "cd .."
  - "cd selendroid-test-app"
  - "gradle assembleDebug"

env:
  global:
    - secure: "qOCTIN+N9lYVx/rp7Qu5xcyaFPLsf64UYSOY5dq+4jOx5vokQfb0vwFxKyDJcUD7ow3GMhw11280HE2OZ3Xk+1xRGWND5Axhey8BPOjqT9D+vjKY2o2Q2ZmUbBTapL/lDixjnV9Gk/bJLytPLNaaA7S/HNfp0g03bWhLanz5fgg="
    - secure: "BzwsXUidLx7X733KzZDwvuXsIiFD0WazDABk8FM3BuvkJnGd8xp84A0ZwZ76PYvrxWp/MncyaOytkrnNA86rnBmpWvcnWzEuBVoDY/cEc4q1SnLjgsRByanNBPoYopFHAVRI2zvkU8hSBVFZC2+ABi3vpNhgYr0LtBhZouBTX5E="
